version: '3.7'
services:
  server:
    container_name: ${REPOSITORY_NAME}-server
    image: ${REPOSITORY_NAME}:latest
    build: .
    ports:
      - '${PORT}:3000'
    environment:
      - DATABASE_URI=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
  postgres:
    container_name: ${REPOSITORY_NAME}-postgres
    image: postgres:latest
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - '${PWD}/.cache/postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
    mem_limit: 1024m
    mem_reservation: 512M
    cpus: 0.5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024m
        reservations:
          cpus: '0.25'
          memory: 512M
